### ISSUE TITLE
Investigate RavenDB package failing to get version number.

### ISSUE THREAD

**Issue by TraGicCode** [TraGicCode/chocolatey-packages#37]

**Comment by rallman** [comment]
@TraGicCode, it looks like RavenDB moved their json file.  `update.ps1` is looking for embedded json in `https://ravendb.net/downloads` (which now redirects to `/download`). The download page now grabs the json content from `https://ravendb.net/wp-json/ravendb/downloads`. 

The content of the json could have changed as well since the checksum doesn't seem to be included.

**Comment by TraGicCode** [comment]
Hey @rallman ,

Thanks Rallman.  I will fix this today.

**Comment by rallman** [comment]
Thanks very much. We are back to choco installing the latest now. I appreciate your work!
